"""
Web Registry Generator for HVANTK Dataset Validation

This module provides web interface generation capabilities for the dataset
validation registry system.
"""
import logging
from pathlib import Path
from typing import Optional, Dict, Any
from collections import Counter

from .config import RegistryConfig

logger = logging.getLogger(__name__)


class WebRegistryGenerator:
    """
    Generator for web-based registry interfaces.

    This class creates HTML-based web interfaces for browsing and
    visualizing dataset validation results.
    """

    def __init__(self, config: Optional[RegistryConfig] = None):
        """
        Initialize the web registry generator.

        Args:
            config: Registry configuration object
        """
        self.config = config or RegistryConfig()
        logger.info("WebRegistryGenerator initialized")

    def generate_web_registry(self, registry_file: str, output_dir: str) -> Path:
        """
        Generate a complete web interface for the registry.

        Args:
            registry_file: Path to the validation registry JSON file
            output_dir: Directory to output web files

        Returns:
            Path to the generated web interface directory

        Raises:
            NotImplementedError: This is a stub implementation
        """
        logger.warning("WebRegistryGenerator.generate_web_registry called - stub implementation")

        # Create output directory if it doesn't exist
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        # Get timestamp
        timestamp = Path(registry_file).stat().st_mtime if Path(registry_file).exists() else "unknown"

        # Create a basic index.html file as a placeholder
        index_file = output_path / "index.html"
        with open(index_file, 'w') as f:
            f.write(f"""<!DOCTYPE html>
<html>
<head>
    <title>HVANTK Dataset Registry</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="header">
        <h1>HVANTK Dataset Validation Registry</h1>
    </div>
    <div class="notice">
        <h3>Stub Implementation</h3>
        <p>This is a placeholder web interface generated by the stub WebRegistryGenerator.</p>
        <p>Registry file: {registry_file}</p>
        <p>Generated on: {timestamp}</p>
    </div>
    <p>A complete web interface implementation would display:</p>
    <ul>
        <li>Dataset validation results</li>
        <li>Statistics and summaries</li>
        <li>Failed dataset details</li>
        <li>Interactive filtering and search</li>
    </ul>
</body>
</html>""")

        # Create a basic styles.css file
        css_file = output_path / "styles.css"
        with open(css_file, 'w') as f:
            f.write("""/* HVANTK Dataset Registry Styles */
body {
    font-family: Arial, sans-serif;
    margin: 40px;
    background-color: #f8f9fa;
}

.header {
    color: #333;
    border-bottom: 2px solid #eee;
    padding-bottom: 10px;
    margin-bottom: 20px;
}

.notice {
    background: #fff3cd;
    border: 1px solid #ffeaa7;
    padding: 15px;
    margin: 20px 0;
    border-radius: 4px;
}

ul {
    list-style-type: disc;
    margin-left: 20px;
}

li {
    margin: 5px 0;
}
""")

        logger.info(f"Generated stub web interface at {index_file}")
        logger.info(f"Generated CSS file at {css_file}")
        return output_path

    def generate_dashboard(self, registry_file: str, output_file: str) -> Path:
        """
        Generate a dashboard view of registry statistics.

        Args:
            registry_file: Path to the validation registry JSON file
            output_file: Path to output dashboard HTML file

        Returns:
            Path to the generated dashboard file

        Raises:
            NotImplementedError: This is a stub implementation
        """
        logger.warning("WebRegistryGenerator.generate_dashboard called - stub implementation")

        output_path = Path(output_file)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        with open(output_path, 'w') as f:
            f.write("""<!DOCTYPE html>
<html>
<head>
    <title>HVANTK Registry Dashboard</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .dashboard { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; }
        .card { border: 1px solid #ddd; padding: 20px; border-radius: 8px; background: #f9f9f9; }
        .notice { background: #fff3cd; border: 1px solid #ffeaa7; padding: 15px; margin: 20px 0; border-radius: 4px; }
    </style>
</head>
<body>
    <h1>HVANTK Registry Dashboard</h1>
    <div class="notice">
        <p><strong>Stub Implementation:</strong> This dashboard would normally display real-time statistics from the registry.</p>
    </div>
    <div class="dashboard">
        <div class="card">
            <h3>Dataset Summary</h3>
            <p>Total datasets, success rates, and validation status breakdown would appear here.</p>
        </div>
        <div class="card">
            <h3>Recent Activity</h3>
            <p>Recently validated datasets and their results would be listed here.</p>
        </div>
        <div class="card">
            <h3>Failed Validations</h3>
            <p>Details about failed validations and error messages would be shown here.</p>
        </div>
    </div>
</body>
</html>""")

        logger.info(f"Generated stub dashboard at {output_path}")
        return output_path

    def generate_status_badge(self, status: str) -> str:
        """
        Generate an SVG status badge for a validation status.

        Args:
            status: Validation status (e.g., 'tier3_passed', 'tier1_failed')

        Returns:
            SVG string representing the status badge
        """
        # Define status colors and labels
        status_config = {
            'tier3_passed': {'color': '#28a745', 'label': 'Tier3 Passed'},
            'tier2_passed': {'color': '#28a745', 'label': 'Tier2 Passed'},
            'tier1_passed': {'color': '#17a2b8', 'label': 'Tier1 Passed'},
            'tier3_failed': {'color': '#dc3545', 'label': 'Tier3 Failed'},
            'tier2_failed': {'color': '#dc3545', 'label': 'Tier2 Failed'},
            'tier1_failed': {'color': '#dc3545', 'label': 'Tier1 Failed'},
            'not_validated': {'color': '#6c757d', 'label': 'Not Validated'},
            'in_progress': {'color': '#ffc107', 'label': 'In Progress'}
        }

        config = status_config.get(status, {'color': '#6c757d', 'label': 'Unknown'})

        badge_svg = f'''<!-- Status badge for {status} -->
<svg xmlns="http://www.w3.org/2000/svg" width="104" height="20">
            <linearGradient id="b" x2="0" y2="100%">
                <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
                <stop offset="1" stop-opacity=".1"/>
            </linearGradient>
            <clipPath id="a">
                <rect width="104" height="20" rx="3" fill="#fff"/>
            </clipPath>
            <g clip-path="url(#a)">
                <path fill="#555" d="M0 0h63v20H0z"/>
                <path fill="{config['color']}" d="M63 0h41v20H63z"/>
                <path fill="url(#b)" d="M0 0h104v20H0z"/>
            </g>
            <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="110">
                <text x="325" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="530">badge</text>
                <text x="325" y="140" transform="scale(.1)" textLength="530">badge</text>
                <text x="825" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="310">{config['label']}</text>
                <text x="825" y="140" transform="scale(.1)" textLength="310">{config['label']}</text>
            </g>
        </svg>'''

        return badge_svg

    def generate_summary_stats(self, registry: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generate summary statistics from registry data.

        Args:
            registry: Dictionary containing registry data with dataset information

        Returns:
            Dictionary with summary statistics including total, successful, failed counts and success rate
        """
        if not registry:
            return {
                'total': 0,
                'successful': 0,
                'failed': 0,
                'success_rate': 0.0
            }

        total = len(registry)
        status_counts = Counter(data.get('status', 'unknown') for data in registry.values())

        # Define successful statuses
        successful_statuses = {'tier3_passed', 'tier2_passed', 'tier1_passed'}
        successful = sum(count for status, count in status_counts.items()
                        if status in successful_statuses)

        failed = total - successful
        success_rate = round((successful / total * 100) if total > 0 else 0.0, 1)

        return {
            'total': total,
            'successful': successful,
            'failed': failed,
            'success_rate': success_rate,
            'status_breakdown': dict(status_counts)
        }
