name: hvantk
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10,<3.13
  - pip
  - pip:
      - click
      - hail
      - requests
      - tqdm
      - pandas
      - numpy
      - matplotlib
