"""Snapshot round-trip test for the PeptideAtlas phospho builder.

Builds ``build_peptideatlas_phospho`` from the committed fixture and asserts the
schema and a sample of rows against committed snapshots, so a change in the
builder's contract (the intermediate-TSV -> AnnotationTable mapping) shows up as
an explicit diff rather than silently.

Fixture provenance -- READ THIS BEFORE TRUSTING THE NUMBERS
-------------------------------------------------------------
``testdata/raw/peptideatlas-phospho/peptideatlas-phospho-synthetic.tsv`` is a
**synthetic miniature**, not a truncation of a real PeptideAtlas build: the real
``atlas_build_*.tsv.zip`` is ~549 MB (``content_length`` in the committed
``tests/drift_fingerprint.json``) and is not (and should not be) vendored
into this repo. It was generated by running the *real* parse pipeline
(``parse_peptideatlas_zip`` + ``write_intermediate_tsv`` from
``hvantk/skills/peptideatlas/phospho/shared/datasets.py``) over the exact mock
zip construction already used by ``test_phospho.py::mock_pa_zip`` -- a
miniature TP53 (P04637) protein with two phospho sites (Ser315, observed by two
peptides whose counts sum to 80; Ser6, observed once with count 10), plus a
DECOY_ accession that the parser must drop.

Regenerate with (copy the body of ``mock_pa_zip`` out of ``test_phospho.py`` --
it is the source of truth for the shape of this fixture):

    import zipfile
    from pathlib import Path
    from hvantk.skills.peptideatlas.phospho.shared.datasets import (
        parse_peptideatlas_zip, write_intermediate_tsv,
    )
    # ... build the same mock zip as test_phospho.py::mock_pa_zip ...
    sites = parse_peptideatlas_zip(str(zip_path))
    write_intermediate_tsv(sites, "peptideatlas-phospho-synthetic.tsv")

What this test does and does not cover
---------------------------------------
This test exercises the intermediate-TSV -> ``AnnotationTable`` contract that
``build_peptideatlas_phospho`` actually implements (a thin ``pd.read_csv`` +
``AnnotationTable.from_pandas`` wrap -- see ``builder.py``'s module docstring).
It does NOT exercise upstream PeptideAtlas zip parsing (table joins, phospho
offset extraction, canonical-protein / DECOY filtering, observation-count
aggregation) -- that is already covered separately by
``hvantk/skills/peptideatlas/phospho/tests/test_phospho.py``.

Why this does not use ``hvantk.tests._snapshot_utils.regenerate_snapshots``
------------------------------------------------------------------------------
``build_peptideatlas_phospho`` returns a **pandas-backed** ``AnnotationTable``
(``peptideatlas`` has no native Hail/AnnData representation -- see
``builder.py``). ``regenerate_snapshots`` only has two dispatch branches: one
for ``anndata.AnnData`` and a Hail-table fallback that re-reads whatever was
written to an ``output_path``. Neither is a true fit: this artifact is not
AnnData, and forcing it through the Hail branch would only work via
``AnnotationTable.to_hail()`` (which drops the pandas dtypes and requires a
full Hail/Spark session, `@pytest.mark.hail`, just to validate a builder that
never touches Hail -- see ``hail_session`` cost in ``hvantk/tests/conftest.py``
and CLAUDE.md's "one contract per layer" guidance). ``AnnotationTable`` already
computes its own backend-agnostic ``.schema`` dict
(``hvantk/core/models/annotation_table.py::_normalize_dtype``), so this test
uses that directly plus a small local helper mirroring ``collect_sample_rows``'
``{"key": ..., "row": ...}`` shape, and still uses ``_snapshot_utils.load_snapshot``
for the read side. This keeps the test Hail-free, matching every other
pure-pandas plugin path and the default (non-``-m hail``) pytest selection.

Regenerate after an intentional change:
    pytest hvantk/skills/peptideatlas/phospho/tests/test_builder.py --regenerate-snapshots
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import pytest

from hvantk.tests._snapshot_utils import load_snapshot

FIXTURE = str(
    Path("hvantk/skills/peptideatlas/phospho/tests/testdata/raw/peptideatlas-phospho")
    / "peptideatlas-phospho-synthetic.tsv"
)
SNAPSHOT_DIR = Path("hvantk/skills/peptideatlas/phospho/tests/snapshots")

EXPECTED_COLUMNS = {
    "accession",
    "gene_symbol",
    "position",
    "description",
    "amino_acid",
    "ensembl_xrefs",
    "sequence_length",
    "n_observations",
    "source_db",
    "evidence_type",
}

# (accession, position) is the composite identity parse_peptideatlas_zip already
# dedupes/aggregates phospho sites on -- the natural row key for this table, even
# though the pandas-backed AnnotationTable itself carries no formal key concept.
KEY_FIELDS = ("accession", "position")

# Real keys, taken from an actual build of the fixture (P04637 Ser315 / Ser6) -- row
# selection below raises KeyError for any key absent from the table, so these cannot
# be invented.
SAMPLE_KEYS = [
    {"accession": "P04637", "position": "315"},
    {"accession": "P04637", "position": "6"},
]


def _fake_ctx():
    """Deterministic BuildContext, so provenance never perturbs a snapshot."""
    from hvantk.core.models.build_context import BuildContext

    return BuildContext(
        plugin="peptideatlas",
        dataset="peptideatlas:phospho",
        plugin_version="test",
        source_fingerprint="sha256:test",
        builder_commit=None,
    )


def _build(fixture_path: str = FIXTURE):
    """Run the builder under test against the fixture."""
    from hvantk.skills.peptideatlas.phospho.builder import build_peptideatlas_phospho

    return build_peptideatlas_phospho(parsed_input=fixture_path, ctx=_fake_ctx())


def _schema_to_dict(artifact, df) -> dict:
    """JSON-stable schema dict: ordered columns + AnnotationTable's normalized dtypes."""
    return {
        "n_rows": int(len(df)),
        "columns": list(df.columns),
        "dtypes": artifact.schema,
    }


def _sample_rows(df, keys: list[dict]) -> list[dict]:
    """Select rows by (accession, position), in the order of ``keys``.

    Mirrors ``_snapshot_utils.collect_sample_rows``'s ``{"key": ..., "row": ...}``
    shape and its fail-loudly-on-missing-key behavior (a silently dropped key would
    produce a confusing snapshot diff instead of an explicit error).
    """
    out = []
    for k in keys:
        mask = None
        for field in KEY_FIELDS:
            field_mask = df[field] == k[field]
            mask = field_mask if mask is None else (mask & field_mask)
        matches = df[mask]
        if matches.empty:
            available = list(zip(df["accession"], df["position"]))[:5]
            raise KeyError(
                f"requested key {k!r} not found in table; "
                f"available keys: {available} (showing up to 5)"
            )
        row = matches.iloc[0]
        # pd.read_csv(..., dtype=str) still applies pandas' default NA detection, so an
        # empty field (e.g. ensembl_xrefs, always "" in write_intermediate_tsv today)
        # comes back as float NaN inside an otherwise-str column, not "". Normalize to
        # None: NaN != NaN in Python, which would make every round trip "drift" even
        # when nothing changed, and None survives a JSON write/read unchanged.
        out.append(
            {
                "key": {f: row[f] for f in KEY_FIELDS},
                "row": {
                    c: (None if pd.isna(row[c]) else row[c])
                    for c in df.columns
                    if c not in KEY_FIELDS
                },
            }
        )
    return out


def test_peptideatlas_phospho_snapshot_round_trip(regenerate_snapshots):
    """Build peptideatlas:phospho from fixture; assert schema and sample-row stability."""
    artifact = _build()
    df = artifact.to_pandas()

    # Structural assertions, independent of the snapshot comparison.
    assert len(df) == 2, "fixture has exactly two phospho sites (Ser315, Ser6)"
    assert set(df.columns) == EXPECTED_COLUMNS, (
        "intermediate-TSV column set drifted from the 10-column contract in "
        "shared/datasets.py::_TSV_COLUMNS"
    )

    if regenerate_snapshots:
        SNAPSHOT_DIR.mkdir(parents=True, exist_ok=True)
        schema = _schema_to_dict(artifact, df)
        (SNAPSHOT_DIR / "schema.json").write_text(json.dumps(schema, indent=2, sort_keys=True))
        rows = _sample_rows(df, SAMPLE_KEYS)
        (SNAPSHOT_DIR / "sample_rows.json").write_text(json.dumps(rows, indent=2, sort_keys=True))
        pytest.skip("Snapshots regenerated; rerun without --regenerate-snapshots to assert.")

    expected_schema = load_snapshot(SNAPSHOT_DIR / "schema.json")
    assert _schema_to_dict(artifact, df) == expected_schema, (
        "peptideatlas:phospho schema drifted from snapshot"
    )

    expected_rows = load_snapshot(SNAPSHOT_DIR / "sample_rows.json")
    assert _sample_rows(df, SAMPLE_KEYS) == expected_rows, (
        "peptideatlas:phospho sample rows drifted from snapshot"
    )
