"""Render a CohortManifest stub describing a ``hvantk cohort burden`` output table.

The burden op writes a gene table whose columns are fixed (``minp`` plus the architecture
reductions ``n_case_var``/``conc``/``driver_af``). This renders the matching ``cohort.yaml``
so a user doesn't hand-author it -- the last bit of friction in the originate-a-prior ->
``rerank`` loop. Pure Python (no Hail): fast-testable.
"""
from __future__ import annotations

import yaml

# The architecture reductions the burden op always emits, and that
# CaseControlArchitectureAudit consumes (see hvantk.algorithms.rerank.audit).
ARCHITECTURE_AXIS_COLUMNS = ("n_case_var", "conc", "driver_af")

_HEADER = (
    "# Generated by `hvantk cohort burden --emit-manifest`. Edit freely.\n"
    "# prior = the burden min-p; the `architecture` axis auto-wires the advisory\n"
    "# CaseControlArchitectureAudit in `hvantk rerank`. Add a `labels:` block\n"
    "# (a GeneSetCollection path) before reranking -- rerank requires labels.\n"
)


def render_cohort_manifest(
    *,
    name: str,
    key: str,
    table: str,
    key_column: str = "gene",
    prior_column: str = "minp",
    architecture_columns=ARCHITECTURE_AXIS_COLUMNS,
) -> str:
    """Return ``cohort.yaml`` text for a gene-level cohort table.

    ``key`` is the gene-key space (``gene_id``/``hgnc_id``/``symbol``); ``key_column``
    is the burden output's gene column (usually ``gene``); ``table`` is the output TSV
    path (kept verbatim -- consumers resolve it relative to their working directory).

    The defaults describe ``hvantk cohort burden``'s own output. They are parameters
    because the manifest is the contract for EXTERNAL cohorts too, and those rarely
    match:

    ``prior_column``
        The burden op writes ``minp``, but a consumed prior is usually named something
        else -- Epi25 DEE uses ``p_dee``, SCHEMA uses ``p_burden``. Hardcoding ``minp``
        emits a manifest that validates and then resolves to a missing column.

    ``architecture_columns``
        Pass ``None`` for a cohort with no variant-level table, which therefore has no
        allelic-architecture columns and no artifact veto. Emitting the axis anyway
        would name columns the table does not have, and would hide a real difference
        between cohorts behind a block that looks populated.
    """
    doc = {
        "name": name,
        "key": key,
        "key_column": key_column,
        "table": table,
        "prior": {"column": prior_column, "direction": "lower_is_better"},
    }
    if architecture_columns:
        doc["cohort_axes"] = [
            {"axis": "architecture", "columns": list(architecture_columns)}
        ]
    return _HEADER + yaml.safe_dump(doc, sort_keys=False)
