"""Tests for ancestry filter module.

These tests require Hail and use synthetic MatrixTables generated by
the Balding-Nichols population genetics model.
"""

import pytest

from hvantk.ancestry.filter import (
    filter_to_autosomes,
    filter_to_biallelic_snps,
    compute_variant_qc,
    filter_variants_for_ancestry,
    ld_prune_variants,
    prepare_ancestry_variants,
)


@pytest.mark.hail
class TestFilterToAutosomes:
    """Tests for filter_to_autosomes function."""

    def test_autosomes_only(self, hail_session, small_merged_mt):
        """Filter should keep only autosomal variants."""
        mt_filtered = filter_to_autosomes(small_merged_mt)

        # All remaining variants should be on autosomes
        # Balding-Nichols generates on chromosome 1 by default
        n_filtered = mt_filtered.count_rows()
        assert n_filtered > 0

        # Verify all loci are autosomal
        non_autosomal = mt_filtered.filter_rows(
            ~mt_filtered.locus.in_autosome()
        ).count_rows()
        assert non_autosomal == 0


@pytest.mark.hail
class TestFilterToBiallelicSnps:
    """Tests for filter_to_biallelic_snps function."""

    def test_biallelic_snps_only(self, hail_session, small_merged_mt):
        """Filter should keep only biallelic SNPs."""
        import hail as hl

        mt_filtered = filter_to_biallelic_snps(small_merged_mt)

        # Check all variants are biallelic
        n_multiallelic = mt_filtered.filter_rows(
            hl.len(mt_filtered.alleles) != 2
        ).count_rows()
        assert n_multiallelic == 0

        # Check all variants are SNPs
        n_non_snp = mt_filtered.filter_rows(
            ~hl.is_snp(mt_filtered.alleles[0], mt_filtered.alleles[1])
        ).count_rows()
        assert n_non_snp == 0


@pytest.mark.hail
class TestComputeVariantQc:
    """Tests for compute_variant_qc function."""

    def test_adds_variant_qc_annotation(self, hail_session, small_merged_mt):
        """Should add variant_qc row annotation."""
        mt_qc = compute_variant_qc(small_merged_mt)

        assert "variant_qc" in mt_qc.row

    def test_variant_qc_has_expected_fields(self, hail_session, small_merged_mt):
        """variant_qc should have expected fields."""
        mt_qc = compute_variant_qc(small_merged_mt)

        # Check expected fields exist
        variant_qc_fields = list(mt_qc.variant_qc)
        assert "call_rate" in variant_qc_fields
        assert "AF" in variant_qc_fields
        assert "n_called" in variant_qc_fields

    def test_idempotent(self, hail_session, small_merged_mt):
        """Calling compute_variant_qc twice should not fail."""
        mt_qc1 = compute_variant_qc(small_merged_mt)
        mt_qc2 = compute_variant_qc(mt_qc1)

        # Should have same structure
        assert list(mt_qc1.row) == list(mt_qc2.row)


@pytest.mark.hail
class TestFilterVariantsForAncestry:
    """Tests for filter_variants_for_ancestry function."""

    def test_basic_filtering(self, hail_session, small_merged_mt):
        """Basic filtering should reduce variant count."""
        n_before = small_merged_mt.count_rows()

        mt_filtered = filter_variants_for_ancestry(
            small_merged_mt,
            min_af=0.01,
            max_af=0.99,
            min_call_rate=0.98,
        )

        n_after = mt_filtered.count_rows()

        # Filtering should remove some variants
        # (though with synthetic data, most may pass)
        assert n_after > 0
        assert n_after <= n_before

    def test_has_variant_qc_annotation(self, hail_session, small_merged_mt):
        """Filtered MT should have variant_qc annotation."""
        mt_filtered = filter_variants_for_ancestry(small_merged_mt)

        assert "variant_qc" in mt_filtered.row

    def test_respects_af_threshold(self, hail_session, small_merged_mt):
        """Should filter by allele frequency thresholds."""
        min_af = 0.1
        max_af = 0.9

        mt_filtered = filter_variants_for_ancestry(
            small_merged_mt,
            min_af=min_af,
            max_af=max_af,
        )

        # Check all remaining variants meet AF criteria
        # Collect AF values - use rows table directly with its own field reference
        rows_ht = mt_filtered.rows()
        af_values = (
            rows_ht
            .select(af=rows_ht.variant_qc.AF[1])
            .to_pandas()["af"]
        )

        assert (af_values >= min_af).all()
        assert (af_values <= max_af).all()

    def test_respects_call_rate_threshold(self, hail_session, small_merged_mt):
        """Should filter by call rate threshold."""
        min_call_rate = 0.99

        mt_filtered = filter_variants_for_ancestry(
            small_merged_mt,
            min_call_rate=min_call_rate,
        )

        # Check all remaining variants meet call rate criteria
        # Use rows table directly with its own field reference
        rows_ht = mt_filtered.rows()
        call_rates = (
            rows_ht
            .select(cr=rows_ht.variant_qc.call_rate)
            .to_pandas()["cr"]
        )

        assert (call_rates >= min_call_rate).all()

    def test_invalid_min_af_raises(self, hail_session, small_merged_mt):
        """Invalid min_af should raise ValueError."""
        with pytest.raises(ValueError, match="min_af"):
            filter_variants_for_ancestry(small_merged_mt, min_af=-0.1)

        with pytest.raises(ValueError, match="min_af"):
            filter_variants_for_ancestry(small_merged_mt, min_af=1.0)

    def test_invalid_max_af_raises(self, hail_session, small_merged_mt):
        """Invalid max_af should raise ValueError."""
        with pytest.raises(ValueError, match="max_af"):
            filter_variants_for_ancestry(small_merged_mt, max_af=0.0)

        with pytest.raises(ValueError, match="max_af"):
            filter_variants_for_ancestry(small_merged_mt, max_af=1.5)

    def test_min_af_greater_than_max_af_raises(self, hail_session, small_merged_mt):
        """min_af >= max_af should raise ValueError."""
        with pytest.raises(ValueError, match="min_af.*must be less than max_af"):
            filter_variants_for_ancestry(small_merged_mt, min_af=0.5, max_af=0.3)


@pytest.mark.hail
@pytest.mark.slow
class TestLdPruneVariants:
    """Tests for ld_prune_variants function.

    These tests are marked slow because LD pruning can be time-consuming.
    """

    def test_reduces_variant_count(self, hail_session, small_merged_mt):
        """LD pruning should reduce the number of variants."""
        # First filter to get a reasonable variant set
        mt_filtered = filter_variants_for_ancestry(small_merged_mt)
        n_before = mt_filtered.count_rows()

        mt_pruned = ld_prune_variants(
            mt_filtered,
            r2=0.2,
            bp_window_size=500_000,
        )

        n_after = mt_pruned.count_rows()

        # LD pruning should remove some variants
        assert n_after > 0
        assert n_after <= n_before

    def test_preserves_gt_field(self, hail_session, small_merged_mt):
        """LD-pruned MT should still have GT field."""
        mt_filtered = filter_variants_for_ancestry(small_merged_mt)
        mt_pruned = ld_prune_variants(mt_filtered)

        assert "GT" in mt_pruned.entry


@pytest.mark.hail
@pytest.mark.slow
class TestPrepareAncestryVariants:
    """Tests for prepare_ancestry_variants convenience function."""

    def test_applies_all_filters(self, hail_session, small_merged_mt):
        """Should apply filtering and LD pruning."""
        n_initial = small_merged_mt.count_rows()

        mt_prepared = prepare_ancestry_variants(
            small_merged_mt,
            min_af=0.05,
            min_call_rate=0.95,
            ld_r2=0.2,
        )

        n_final = mt_prepared.count_rows()

        # Should reduce variant count
        assert n_final > 0
        assert n_final <= n_initial

    def test_skip_ld_pruning(self, hail_session, small_merged_mt):
        """Should skip LD pruning when requested."""
        # With LD pruning
        mt_with_ld = prepare_ancestry_variants(
            small_merged_mt,
            skip_ld_pruning=False,
        )

        # Without LD pruning
        mt_without_ld = prepare_ancestry_variants(
            small_merged_mt,
            skip_ld_pruning=True,
        )

        # Without LD pruning should have more or equal variants
        assert mt_without_ld.count_rows() >= mt_with_ld.count_rows()
