"""Integration tests for ancestry inference pipeline.

These tests verify the end-to-end pipeline functionality using synthetic
genetic data generated by the Balding-Nichols model.
"""

import pytest
import tempfile
from pathlib import Path

from hvantk.ancestry.pipeline import (
    PipelineConfig,
    AncestryInferenceResult,
    run_ancestry_inference,
)
from hvantk.ancestry.constants import (
    ANCESTRY_PROB_COL,
    KNOWN_ANCESTRY_COL,
    PREDICTED_ANCESTRY_COL,
    SOURCE_COL,
)


class TestPipelineConfig:
    """Tests for PipelineConfig dataclass."""

    def test_default_config(self):
        """Default config should have expected values."""
        config = PipelineConfig()

        assert config.min_af == 0.01
        assert config.max_af == 0.99
        assert config.min_call_rate == 0.98
        assert config.ld_r2 == 0.2
        assert config.n_pcs == 20
        assert config.n_pcs_classify == 10
        assert config.min_prob == 0.75
        assert config.validate_model is True

    def test_custom_config(self):
        """Custom config values should be set correctly."""
        config = PipelineConfig(
            min_af=0.05,
            min_prob=0.80,
            n_pcs_classify=15,
            skip_ld_pruning=True,
        )

        assert config.min_af == 0.05
        assert config.min_prob == 0.80
        assert config.n_pcs_classify == 15
        assert config.skip_ld_pruning is True

    def test_to_dict(self):
        """Config should serialize to dictionary."""
        config = PipelineConfig(min_af=0.05)
        d = config.to_dict()

        assert isinstance(d, dict)
        assert d["min_af"] == 0.05
        assert "n_pcs" in d
        assert "min_prob" in d

    def test_from_dict(self):
        """Config should deserialize from dictionary."""
        d = {"min_af": 0.05, "min_prob": 0.80, "n_pcs": 15}
        config = PipelineConfig.from_dict(d)

        assert config.min_af == 0.05
        assert config.min_prob == 0.80
        assert config.n_pcs == 15

    def test_from_dict_ignores_unknown(self):
        """from_dict should ignore unknown keys."""
        d = {"min_af": 0.05, "unknown_param": "value"}
        config = PipelineConfig.from_dict(d)

        assert config.min_af == 0.05
        assert not hasattr(config, "unknown_param")


@pytest.mark.hail
class TestRunAncestryInference:
    """Integration tests for run_ancestry_inference function."""

    def test_basic_pipeline(
        self, hail_session, synthetic_query_mt, synthetic_reference_mt
    ):
        """Basic pipeline should complete successfully."""
        result = run_ancestry_inference(
            query_mt=synthetic_query_mt,
            reference_mt=synthetic_reference_mt,
            ancestry_col="ancestry",
            config=PipelineConfig(
                skip_ld_pruning=True,  # Skip for speed in tests
                min_shared_variants=100,
                validate_model=False,  # Skip for speed
            ),
        )

        assert isinstance(result, AncestryInferenceResult)
        assert result.predictions is not None
        assert result.pc_scores is not None
        assert result.model is not None
        assert result.loadings is not None
        assert len(result.eigenvalues) > 0

    def test_pipeline_with_validation(
        self, hail_session, synthetic_query_mt, synthetic_reference_mt
    ):
        """Pipeline with validation should include accuracy metrics."""
        result = run_ancestry_inference(
            query_mt=synthetic_query_mt,
            reference_mt=synthetic_reference_mt,
            ancestry_col="ancestry",
            config=PipelineConfig(
                skip_ld_pruning=True,
                min_shared_variants=100,
                validate_model=True,
                n_cv_folds=3,  # Fewer folds for speed
            ),
        )

        # Should have validation metrics
        accuracy = result.get_accuracy()
        assert accuracy is not None
        assert 0.0 <= accuracy <= 1.0

        # Should be in pipeline stats
        assert "cv_accuracy" in result.pipeline_stats

    def test_pipeline_stats_populated(
        self, hail_session, synthetic_query_mt, synthetic_reference_mt
    ):
        """Pipeline stats should contain expected fields."""
        result = run_ancestry_inference(
            query_mt=synthetic_query_mt,
            reference_mt=synthetic_reference_mt,
            ancestry_col="ancestry",
            config=PipelineConfig(
                skip_ld_pruning=True,
                min_shared_variants=100,
                validate_model=False,
            ),
        )

        stats = result.pipeline_stats

        # Check required stats
        assert "n_query_samples" in stats
        assert "n_reference_samples" in stats
        assert "n_merged_samples" in stats
        assert "n_shared_variants" in stats
        assert "n_variants_after_filter" in stats
        assert "n_training_samples" in stats
        assert "n_populations" in stats
        assert "n_query_assigned" in stats
        assert "n_query_unassigned" in stats

    def test_predictions_structure(
        self, hail_session, synthetic_query_mt, synthetic_reference_mt
    ):
        """Predictions DataFrame should have expected structure."""
        result = run_ancestry_inference(
            query_mt=synthetic_query_mt,
            reference_mt=synthetic_reference_mt,
            ancestry_col="ancestry",
            config=PipelineConfig(
                skip_ld_pruning=True,
                min_shared_variants=100,
                validate_model=False,
            ),
        )

        predictions_df = result.get_predictions_df()

        # Check required columns
        assert "s" in predictions_df.columns
        assert PREDICTED_ANCESTRY_COL in predictions_df.columns
        assert ANCESTRY_PROB_COL in predictions_df.columns
        assert SOURCE_COL in predictions_df.columns
        assert KNOWN_ANCESTRY_COL in predictions_df.columns

        # Check PC columns
        assert "PC1" in predictions_df.columns
        assert "PC2" in predictions_df.columns

        # Check sample count
        n_query = synthetic_query_mt.count_cols()
        n_ref = synthetic_reference_mt.count_cols()
        assert len(predictions_df) == n_query + n_ref

    def test_query_predictions(
        self, hail_session, synthetic_query_mt, synthetic_reference_mt
    ):
        """Query predictions should be correctly filtered."""
        result = run_ancestry_inference(
            query_mt=synthetic_query_mt,
            reference_mt=synthetic_reference_mt,
            ancestry_col="ancestry",
            config=PipelineConfig(
                skip_ld_pruning=True,
                min_shared_variants=100,
                validate_model=False,
            ),
        )

        query_preds = result.get_query_predictions()

        # Should have only query samples
        assert all(query_preds[SOURCE_COL] == "query")
        assert len(query_preds) == synthetic_query_mt.count_cols()

        # Query samples should have missing known ancestry
        assert query_preds[KNOWN_ANCESTRY_COL].isna().all()

    def test_reference_predictions(
        self, hail_session, synthetic_query_mt, synthetic_reference_mt
    ):
        """Reference predictions should be correctly filtered."""
        result = run_ancestry_inference(
            query_mt=synthetic_query_mt,
            reference_mt=synthetic_reference_mt,
            ancestry_col="ancestry",
            config=PipelineConfig(
                skip_ld_pruning=True,
                min_shared_variants=100,
                validate_model=False,
            ),
        )

        ref_preds = result.get_reference_predictions()

        # Should have only reference samples
        assert all(ref_preds[SOURCE_COL] == "reference")
        assert len(ref_preds) == synthetic_reference_mt.count_cols()

        # Reference samples should have known ancestry
        assert not ref_preds[KNOWN_ANCESTRY_COL].isna().any()

    def test_prediction_summary(
        self, hail_session, synthetic_query_mt, synthetic_reference_mt
    ):
        """Prediction summary should return ancestry counts."""
        result = run_ancestry_inference(
            query_mt=synthetic_query_mt,
            reference_mt=synthetic_reference_mt,
            ancestry_col="ancestry",
            config=PipelineConfig(
                skip_ld_pruning=True,
                min_shared_variants=100,
                validate_model=False,
            ),
        )

        summary = result.prediction_summary()

        assert isinstance(summary, dict)
        assert sum(summary.values()) == synthetic_query_mt.count_cols()

    def test_variance_explained(
        self, hail_session, synthetic_query_mt, synthetic_reference_mt
    ):
        """Variance explained should be computed correctly."""
        result = run_ancestry_inference(
            query_mt=synthetic_query_mt,
            reference_mt=synthetic_reference_mt,
            ancestry_col="ancestry",
            config=PipelineConfig(
                skip_ld_pruning=True,
                min_shared_variants=100,
                validate_model=False,
                n_pcs=5,
            ),
        )

        var_exp = result.variance_explained()

        assert len(var_exp) == 5
        assert all(0 <= v <= 1 for v in var_exp)
        assert sum(var_exp) <= 1.0

    def test_kwargs_override_config(
        self, hail_session, synthetic_query_mt, synthetic_reference_mt
    ):
        """kwargs should override config values."""
        config = PipelineConfig(min_prob=0.75)

        result = run_ancestry_inference(
            query_mt=synthetic_query_mt,
            reference_mt=synthetic_reference_mt,
            ancestry_col="ancestry",
            config=config,
            min_prob=0.50,  # Override
            skip_ld_pruning=True,
            min_shared_variants=100,
            validate_model=False,
        )

        # Config in result should have overridden value
        assert result.config.min_prob == 0.50


@pytest.mark.hail
class TestAncestryInferenceResult:
    """Tests for AncestryInferenceResult methods."""

    @pytest.fixture
    def pipeline_result(
        self, hail_session, synthetic_query_mt, synthetic_reference_mt
    ):
        """Run pipeline to get result for testing."""
        return run_ancestry_inference(
            query_mt=synthetic_query_mt,
            reference_mt=synthetic_reference_mt,
            ancestry_col="ancestry",
            config=PipelineConfig(
                skip_ld_pruning=True,
                min_shared_variants=100,
                validate_model=True,
                n_cv_folds=3,
            ),
        )

    def test_get_scores_df(self, pipeline_result):
        """get_scores_df should return DataFrame with PC scores."""
        scores_df = pipeline_result.get_scores_df()

        assert "s" in scores_df.columns
        assert "PC1" in scores_df.columns
        assert "PC2" in scores_df.columns
        assert SOURCE_COL in scores_df.columns

    def test_scores_df_cached(self, pipeline_result):
        """get_scores_df should cache result."""
        df1 = pipeline_result.get_scores_df()
        df2 = pipeline_result.get_scores_df()

        assert df1 is df2  # Same object

    def test_predictions_df_cached(self, pipeline_result):
        """get_predictions_df should cache result."""
        df1 = pipeline_result.get_predictions_df()
        df2 = pipeline_result.get_predictions_df()

        assert df1 is df2  # Same object

    def test_save_and_load(self, pipeline_result):
        """Results should save to disk."""
        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = Path(tmpdir) / "ancestry_output"

            saved_paths = pipeline_result.save(
                output_path=output_path,
                save_model=True,
                save_loadings=True,
            )

            # Check files exist
            assert Path(saved_paths["predictions"]).exists()
            assert Path(saved_paths["pc_scores"]).exists()
            assert Path(saved_paths["predictions_tsv"]).exists()
            assert Path(saved_paths["model"]).exists()
            assert Path(saved_paths["loadings"]).exists()
            assert Path(saved_paths["stats"]).exists()

            # Check TSV content
            import pandas as pd
            tsv_df = pd.read_csv(saved_paths["predictions_tsv"], sep="\t")
            assert PREDICTED_ANCESTRY_COL in tsv_df.columns

    def test_annotate_matrixtable(
        self, hail_session, pipeline_result, synthetic_query_mt
    ):
        """annotate_matrixtable should add ancestry columns."""
        annotated_mt = pipeline_result.annotate_matrixtable(synthetic_query_mt)

        col_fields = list(annotated_mt.col)
        assert PREDICTED_ANCESTRY_COL in col_fields
        assert ANCESTRY_PROB_COL in col_fields
        assert "PC1" in col_fields


@pytest.mark.hail
@pytest.mark.slow
class TestPipelineWithLdPruning:
    """Tests for pipeline with LD pruning enabled."""

    def test_pipeline_with_ld_pruning(
        self, hail_session, synthetic_query_mt, synthetic_reference_mt
    ):
        """Pipeline with LD pruning should complete successfully."""
        result = run_ancestry_inference(
            query_mt=synthetic_query_mt,
            reference_mt=synthetic_reference_mt,
            ancestry_col="ancestry",
            config=PipelineConfig(
                skip_ld_pruning=False,  # Enable LD pruning
                ld_r2=0.2,
                min_shared_variants=100,
                validate_model=False,
            ),
        )

        # LD pruning should reduce variant count
        stats = result.pipeline_stats
        assert stats["n_variants_after_ld_prune"] <= stats["n_variants_after_filter"]

        # Should still produce valid predictions
        assert result.predictions.count() > 0


@pytest.mark.hail
class TestPipelineCheckpointing:
    """Tests for pipeline checkpointing functionality."""

    def test_checkpointing_creates_files(
        self, hail_session, synthetic_query_mt, synthetic_reference_mt
    ):
        """Checkpointing should create MT files."""
        with tempfile.TemporaryDirectory() as tmpdir:
            result = run_ancestry_inference(
                query_mt=synthetic_query_mt,
                reference_mt=synthetic_reference_mt,
                ancestry_col="ancestry",
                config=PipelineConfig(
                    skip_ld_pruning=True,
                    min_shared_variants=100,
                    validate_model=False,
                    checkpoint_path=tmpdir,
                ),
            )

            # Check checkpoint files exist
            assert Path(tmpdir, "merged.mt").exists()
            assert Path(tmpdir, "filtered.mt").exists()

            # Result should still be valid
            assert result.predictions.count() > 0


@pytest.mark.hail
class TestPipelineEdgeCases:
    """Tests for pipeline edge cases."""

    def test_min_prob_zero_assigns_all(
        self, hail_session, synthetic_query_mt, synthetic_reference_mt
    ):
        """min_prob=0 should assign all samples."""
        result = run_ancestry_inference(
            query_mt=synthetic_query_mt,
            reference_mt=synthetic_reference_mt,
            ancestry_col="ancestry",
            config=PipelineConfig(
                skip_ld_pruning=True,
                min_shared_variants=100,
                validate_model=False,
                min_prob=0.0,  # Accept all predictions
            ),
        )

        # No samples should be unassigned
        query_preds = result.get_query_predictions()
        n_unassigned = (query_preds[PREDICTED_ANCESTRY_COL] == "unassigned").sum()
        assert n_unassigned == 0

    def test_high_min_prob_increases_unassigned(
        self, hail_session, synthetic_query_mt, synthetic_reference_mt
    ):
        """Higher min_prob should increase unassigned count."""
        # Low threshold
        result_low = run_ancestry_inference(
            query_mt=synthetic_query_mt,
            reference_mt=synthetic_reference_mt,
            ancestry_col="ancestry",
            config=PipelineConfig(
                skip_ld_pruning=True,
                min_shared_variants=100,
                validate_model=False,
                min_prob=0.5,
            ),
        )

        # High threshold
        result_high = run_ancestry_inference(
            query_mt=synthetic_query_mt,
            reference_mt=synthetic_reference_mt,
            ancestry_col="ancestry",
            config=PipelineConfig(
                skip_ld_pruning=True,
                min_shared_variants=100,
                validate_model=False,
                min_prob=0.99,
            ),
        )

        # Higher threshold should have more unassigned
        low_unassigned = result_low.pipeline_stats["n_query_unassigned"]
        high_unassigned = result_high.pipeline_stats["n_query_unassigned"]
        assert high_unassigned >= low_unassigned
