"""Tests for ancestry PCA module.

These tests require Hail and use synthetic MatrixTables generated by
the Balding-Nichols population genetics model.
"""

import pytest

from hvantk.ancestry.pca import (
    PCAResult,
    compute_pca,
)
from hvantk.ancestry.filter import filter_variants_for_ancestry


@pytest.mark.hail
class TestComputePca:
    """Tests for compute_pca function."""

    def test_basic_pca(self, hail_session, small_merged_mt):
        """Basic PCA should succeed and return PCAResult."""
        # First filter variants
        mt = filter_variants_for_ancestry(small_merged_mt)

        result = compute_pca(mt, n_pcs=5)

        assert isinstance(result, PCAResult)
        assert len(result.eigenvalues) == 5
        assert result.n_variants > 0
        assert result.n_samples > 0

    def test_pca_scores_shape(self, hail_session, small_merged_mt):
        """PCA scores should have correct shape."""
        mt = filter_variants_for_ancestry(small_merged_mt)
        n_samples = mt.count_cols()

        result = compute_pca(mt, n_pcs=5)
        scores_df = result.get_scores_df()

        assert len(scores_df) == n_samples
        assert "PC1" in scores_df.columns
        assert "PC2" in scores_df.columns
        assert "PC3" in scores_df.columns
        assert "PC4" in scores_df.columns
        assert "PC5" in scores_df.columns

    def test_pca_loadings_computed(self, hail_session, small_merged_mt):
        """PCA loadings should be computed when requested."""
        mt = filter_variants_for_ancestry(small_merged_mt)

        result = compute_pca(mt, n_pcs=5, compute_loadings=True)

        assert result.loadings is not None
        assert result.loadings.count() > 0
        assert "loadings" in result.loadings.row

    def test_variance_explained(self, hail_session, small_merged_mt):
        """Variance explained should sum to 1."""
        mt = filter_variants_for_ancestry(small_merged_mt)

        result = compute_pca(mt, n_pcs=5)
        var_exp = result.variance_explained()

        # All values should be between 0 and 1
        assert all(0 <= v <= 1 for v in var_exp)
        # Should sum to less than 1 (since we only compute 5 PCs)
        assert sum(var_exp) <= 1.0

    def test_cumulative_variance(self, hail_session, small_merged_mt):
        """Cumulative variance should be monotonically increasing."""
        mt = filter_variants_for_ancestry(small_merged_mt)

        result = compute_pca(mt, n_pcs=5)
        cum_var = result.cumulative_variance()

        # Should be monotonically increasing
        for i in range(1, len(cum_var)):
            assert cum_var[i] >= cum_var[i - 1]

    def test_pca_with_20_pcs(self, hail_session, small_merged_mt):
        """Should compute up to 20 PCs."""
        mt = filter_variants_for_ancestry(small_merged_mt)

        # Request 20 PCs (may get fewer if n_samples or n_variants is limiting)
        result = compute_pca(mt, n_pcs=20)

        assert len(result.eigenvalues) <= 20
        assert result.get_n_pcs() <= 20

    def test_invalid_n_pcs_raises(self, hail_session, small_merged_mt):
        """Invalid n_pcs should raise ValueError."""
        mt = filter_variants_for_ancestry(small_merged_mt)

        with pytest.raises(ValueError, match="n_pcs must be positive"):
            compute_pca(mt, n_pcs=0)

        with pytest.raises(ValueError, match="n_pcs must be positive"):
            compute_pca(mt, n_pcs=-5)

    def test_missing_gt_raises(self, hail_session, small_merged_mt):
        """Missing GT field should raise ValueError."""
        # Create MT without GT field
        mt = filter_variants_for_ancestry(small_merged_mt)
        mt = mt.select_entries()  # Remove all entry fields

        with pytest.raises(ValueError, match="GT field not found"):
            compute_pca(mt, n_pcs=5)


@pytest.mark.hail
class TestPCAResult:
    """Tests for PCAResult dataclass methods."""

    def test_get_scores_df_caching(self, hail_session, small_merged_mt):
        """get_scores_df should cache the DataFrame."""
        mt = filter_variants_for_ancestry(small_merged_mt)
        result = compute_pca(mt, n_pcs=5)

        # First call
        df1 = result.get_scores_df()
        # Second call should return same object
        df2 = result.get_scores_df()

        assert df1 is df2

    def test_get_n_pcs(self, hail_session, small_merged_mt):
        """get_n_pcs should return correct count."""
        mt = filter_variants_for_ancestry(small_merged_mt)
        result = compute_pca(mt, n_pcs=5)

        assert result.get_n_pcs() == 5


@pytest.mark.hail
class TestPcaPopulationStructure:
    """Tests verifying PCA captures population structure."""

    def test_populations_cluster_separately(
        self, hail_session, synthetic_reference_mt
    ):
        """Reference populations should form distinct clusters in PC space."""
        from hvantk.ancestry.filter import filter_variants_for_ancestry

        # Filter and compute PCA on reference only
        mt = filter_variants_for_ancestry(synthetic_reference_mt)
        result = compute_pca(mt, n_pcs=5)

        scores_df = result.get_scores_df()

        # Join with sample metadata to get ancestry
        samples = synthetic_reference_mt.cols().to_pandas()
        scores_with_ancestry = scores_df.merge(
            samples[["s", "ancestry"]], on="s"
        )

        # Check that populations have distinct PC1 and PC2 means
        pop_means = scores_with_ancestry.groupby("ancestry")[["PC1", "PC2"]].mean()

        # There should be at least some separation between populations
        # (with Balding-Nichols FST=0.1, populations should be distinguishable)
        pc1_range = pop_means["PC1"].max() - pop_means["PC1"].min()
        pc2_range = pop_means["PC2"].max() - pop_means["PC2"].min()

        # At least one PC should show meaningful separation
        assert pc1_range > 0.1 or pc2_range > 0.1, (
            "Populations should show separation in PC space"
        )


@pytest.mark.hail
@pytest.mark.slow
class TestProjectSamples:
    """Tests for project_samples function."""

    def test_projection_produces_scores(
        self, hail_session, synthetic_query_mt, synthetic_reference_mt
    ):
        """Projection should produce PC scores for new samples."""
        from hvantk.ancestry.filter import filter_variants_for_ancestry
        from hvantk.ancestry.pca import project_samples

        # Compute PCA on reference
        ref_filtered = filter_variants_for_ancestry(synthetic_reference_mt)
        pca_result = compute_pca(ref_filtered, n_pcs=5, compute_loadings=True)

        # Filter query to same variants
        query_filtered = synthetic_query_mt.semi_join_rows(
            ref_filtered.rows().select()
        )

        # Project query onto reference PC space
        projected = project_samples(
            mt=query_filtered,
            loadings=pca_result.loadings,
            n_pcs=5,
        )

        # Should have same number of samples as query
        assert projected.count() == synthetic_query_mt.count_cols()

        # Should have PC columns
        projected_df = projected.to_pandas()
        assert "PC1" in projected_df.columns
