"""Tests for ancestry merge module.

These tests require Hail and use synthetic MatrixTables generated by
the Balding-Nichols population genetics model.
"""

import pytest

from hvantk.algorithms.ancestry.merge import (
    validate_matrixtable_compatibility,
    get_shared_variants_stats,
    merge_matrixtables,
    check_sample_overlap,
)
from hvantk.algorithms.ancestry.constants import SOURCE_COL, KNOWN_ANCESTRY_COL


@pytest.mark.hail
class TestValidateMatrixtableCompatibility:
    """Tests for validate_matrixtable_compatibility function."""

    def test_compatible_matrixtables(
        self, hail_session, synthetic_query_mt, synthetic_reference_mt
    ):
        """Compatible MTs should pass validation without error."""
        # Should not raise
        validate_matrixtable_compatibility(
            synthetic_query_mt,
            synthetic_reference_mt,
            ancestry_col="ancestry",
        )

    def test_incompatible_row_key(
        self, hail_session, synthetic_query_mt, synthetic_incompatible_mt
    ):
        """MTs with different row keys should fail validation."""
        with pytest.raises(ValueError, match="Row key mismatch"):
            validate_matrixtable_compatibility(
                synthetic_query_mt,
                synthetic_incompatible_mt,
            )

    def test_missing_ancestry_column(
        self, hail_session, synthetic_query_mt, synthetic_reference_mt
    ):
        """Missing ancestry column should fail validation."""
        with pytest.raises(ValueError, match="Ancestry column.*not found"):
            validate_matrixtable_compatibility(
                synthetic_query_mt,
                synthetic_reference_mt,
                ancestry_col="nonexistent_column",
            )


@pytest.mark.hail
class TestGetSharedVariantsStats:
    """Tests for get_shared_variants_stats function."""

    def test_identical_variants(self, hail_session, synthetic_query_mt):
        """Same MT compared to itself should show all variants as shared."""
        mt1_only, mt2_only, shared = get_shared_variants_stats(
            synthetic_query_mt, synthetic_query_mt
        )

        assert mt1_only == 0
        assert mt2_only == 0
        assert shared == synthetic_query_mt.count_rows()

    def test_overlapping_variants(
        self, hail_session, synthetic_query_mt, synthetic_reference_mt
    ):
        """Query and reference should have overlapping variants."""
        mt1_only, mt2_only, shared = get_shared_variants_stats(
            synthetic_query_mt, synthetic_reference_mt
        )

        # Balding-Nichols with same parameters should have same variants
        # (both generated with n_variants=1000)
        assert shared > 0
        # The exact overlap depends on the simulation
        total = mt1_only + mt2_only + shared
        assert total >= shared  # Sanity check


@pytest.mark.hail
class TestMergeMatrixtables:
    """Tests for merge_matrixtables function."""

    def test_basic_merge(
        self, hail_session, synthetic_query_mt, synthetic_reference_mt
    ):
        """Basic merge should combine samples and retain shared variants."""
        merged = merge_matrixtables(
            query_mt=synthetic_query_mt,
            reference_mt=synthetic_reference_mt,
            ancestry_col="ancestry",
            min_shared_variants=100,  # Lower threshold for testing
        )

        # Check sample count
        n_query = synthetic_query_mt.count_cols()
        n_ref = synthetic_reference_mt.count_cols()
        n_merged = merged.count_cols()
        assert n_merged == n_query + n_ref

        # Check column annotations exist
        col_fields = list(merged.col)
        assert SOURCE_COL in col_fields
        assert KNOWN_ANCESTRY_COL in col_fields

    def test_merge_has_gt_field(
        self, hail_session, synthetic_query_mt, synthetic_reference_mt
    ):
        """Merged MT should have GT entry field."""
        merged = merge_matrixtables(
            query_mt=synthetic_query_mt,
            reference_mt=synthetic_reference_mt,
            ancestry_col="ancestry",
            min_shared_variants=100,  # Lower threshold for testing
        )

        assert "GT" in merged.entry

    def test_source_annotation(
        self, hail_session, synthetic_query_mt, synthetic_reference_mt
    ):
        """Source annotation should correctly identify query vs reference samples."""
        merged = merge_matrixtables(
            query_mt=synthetic_query_mt,
            reference_mt=synthetic_reference_mt,
            ancestry_col="ancestry",
            min_shared_variants=100,  # Lower threshold for testing
        )

        # Collect source annotations
        sources = merged.cols().select(SOURCE_COL).to_pandas()

        n_query = (sources[SOURCE_COL] == "query").sum()
        n_ref = (sources[SOURCE_COL] == "reference").sum()

        assert n_query == synthetic_query_mt.count_cols()
        assert n_ref == synthetic_reference_mt.count_cols()

    def test_known_ancestry_annotation(
        self, hail_session, synthetic_query_mt, synthetic_reference_mt
    ):
        """Known ancestry should be populated for reference samples only."""
        merged = merge_matrixtables(
            query_mt=synthetic_query_mt,
            reference_mt=synthetic_reference_mt,
            ancestry_col="ancestry",
            min_shared_variants=100,  # Lower threshold for testing
        )

        # Collect annotations
        annotations = merged.cols().select(SOURCE_COL, KNOWN_ANCESTRY_COL).to_pandas()

        # Query samples should have missing ancestry
        query_ancestry = annotations[annotations[SOURCE_COL] == "query"][
            KNOWN_ANCESTRY_COL
        ]
        assert query_ancestry.isna().all()

        # Reference samples should have ancestry labels
        ref_ancestry = annotations[annotations[SOURCE_COL] == "reference"][
            KNOWN_ANCESTRY_COL
        ]
        assert not ref_ancestry.isna().any()
        assert set(ref_ancestry.unique()) == {"EUR", "AFR", "EAS"}

    def test_merge_with_validation_disabled(
        self, hail_session, synthetic_query_mt, synthetic_reference_mt
    ):
        """Merge should work with validation disabled."""
        merged = merge_matrixtables(
            query_mt=synthetic_query_mt,
            reference_mt=synthetic_reference_mt,
            ancestry_col="ancestry",
            validate=False,
            min_shared_variants=100,  # Lower threshold for testing
        )

        assert merged.count_cols() > 0
        assert merged.count_rows() > 0


@pytest.mark.hail
class TestCheckSampleOverlap:
    """Tests for check_sample_overlap function."""

    def test_no_overlap(self, hail_session, synthetic_query_mt, synthetic_reference_mt):
        """Query and reference with different IDs should have no overlap."""
        n_overlap, overlap_table = check_sample_overlap(
            synthetic_query_mt, synthetic_reference_mt
        )

        assert n_overlap == 0

    def test_self_overlap(self, hail_session, synthetic_query_mt):
        """MT compared to itself should have full overlap."""
        n_overlap, overlap_table = check_sample_overlap(
            synthetic_query_mt, synthetic_query_mt
        )

        assert n_overlap == synthetic_query_mt.count_cols()
