"""Ratchet: every plugin.yaml artifact it declares must exist, or be listed as a known gap.

The plugin contract has each dataset declare a fixture, a schema snapshot, a row snapshot
and a drift fingerprint. The loader resolves those paths but never checks them
(``TestPaths`` is built from ``(plugin_dir / rel).resolve()``, and ``resolve()`` does not
require existence), so a manifest could promise a snapshot it did not ship and still load
clean -- which is how the tree reached 25 dataset declarations against 10 complete ones
with nothing failing.

This test makes the gap explicit and monotonically shrinking:

* a dataset that starts missing an artifact **fails immediately** -- new plugins cannot
  quietly land incomplete;
* a dataset listed here that becomes complete **also fails**, forcing the entry to be
  removed, so the ledger can never overstate the gap.

Deliberately reads the manifests with ``yaml`` instead of going through the registry, so
it needs no Hail and therefore runs in the default ``pytest`` selection. The equivalent
check behind the registry is ``TestPaths.missing_artifacts()``; keeping this one
Hail-free means the ratchet is enforced by every CI run, not only the ``hail``-marked job.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

SKILLS_DIR = Path(__file__).resolve().parents[1] / "skills"

ARTIFACT_FIELDS = ("fixture", "schema_snapshot", "row_snapshot", "drift_fingerprint")

# Datasets that do NOT yet ship every declared artifact, with the fields still missing.
# Shrink this as snapshots land; never grow it for a new provider without a reason here.
#
# Two causes remain, and they are the same in effect: there is no artifact that CAN be
# committed, so these entries are permanent rather than pending.
#   1. no static upstream artifact exists at all -- alphagenome is a credentialed live
#      prediction API, pqtl is publication-only supplementary data.
#   2. licence forbids redistributing rows (cosmic-cgc).
#
# A third cause used to dominate this list -- "simply never seeded, though the builder
# runs from a committed fixture". As of the #341 plugin follow-ups it is empty:
# expression-atlas and peptideatlas were the last two, and both now ship a fixture plus
# schema/row snapshots and a round-trip test, so both left this list. That matters
# beyond tidiness: a dataset with no executable contract cannot be graded, which is why
# the agent-authoring evaluation (#341) could say nothing at all about those five.
#
# History of departures, kept so the list is not re-grown by accident:
#   clingen, gencc, hgnc -- snapshots landed.
#   gevir -- drift fingerprint shipped with the gevir plugin-review work.
#   dbnsfp, gnomad-metrics -- real drift probes replaced their stub sentinels and their
#     baselines were captured from live probe runs. Both had been recorded under issue
#     #177 as having no probeable URL; re-checking showed the gnomAD constraint tables
#     sit in a public GCS bucket returning an MD5 ETag, and that the dbNSFP landing page
#     -- though its advertised S3 archives are all dead (issue #321) -- still exposes a
#     stable release list. (Both previously appeared here twice over: first for a fixture
#     dir never created, then for a missing drift fingerprint.)
#   uniprot-ptm, cptac:expression, cptac:phospho -- had no committed fixture at all,
#     their round-trip tests synthesized inputs into tmp_path. Small fixtures committed.
#   expression-atlas -- fixture derived by truncating the real 116k-transcript x
#     320-sample inputs under hvantk/tests/testdata/raw/expression_atlas/ (#341).
#   peptideatlas -- fixture generated by running the real parse + write_intermediate_tsv
#     pipeline over the miniature build already used by test_phospho.py (#341).
#
# The three entries below are NOT the datasets without a drift probe: every dataset in
# the tree ships a live one. They are the datasets that cannot ship a *fixture* or
# *snapshot* at all.
KNOWN_INCOMPLETE: dict[str, tuple[str, ...]] = {
    "alphagenome:predictions": ("fixture", "schema_snapshot", "row_snapshot"),
    "cosmic-cgc:submissions": ("fixture", "schema_snapshot", "row_snapshot"),
    "pqtl:metrics": ("fixture", "schema_snapshot", "row_snapshot"),
}

# Why each remaining entry can never be completed. Every KNOWN_INCOMPLETE key must appear
# here (enforced below), so a future entry cannot join a list of permanent exemptions
# without someone writing down why it belongs there. If the honest answer is "not seeded
# yet", it does not belong in KNOWN_INCOMPLETE at all -- seed it, as #341 did for
# expression-atlas and peptideatlas.
PERMANENTLY_UNGRADABLE: dict[str, str] = {
    "alphagenome:predictions": (
        "credentialed live prediction API; there is no upstream file to truncate, and "
        "recorded predictions would pin a model version rather than a data release"
    ),
    "cosmic-cgc:submissions": (
        "COSMIC licence forbids redistributing rows, so no fixture may be committed to "
        "a public repository"
    ),
    "pqtl:metrics": (
        "publication-only supplementary data (Fang et al.); no redistributable URL and "
        "no stable artifact to truncate"
    ),
}


def _declared_artifact_gaps() -> dict[str, tuple[str, ...]]:
    """Map ``provider:dataset`` -> declared artifact fields whose file is absent."""
    gaps: dict[str, tuple[str, ...]] = {}
    for manifest_path in sorted(SKILLS_DIR.glob("*/plugin.yaml")):
        manifest = yaml.safe_load(manifest_path.read_text())
        provider = manifest.get("name") or manifest_path.parent.name
        for dataset in manifest.get("datasets", []):
            tests_block = dataset.get("tests") or {}
            missing = tuple(
                field
                for field in ARTIFACT_FIELDS
                if field in tests_block
                and not (manifest_path.parent / tests_block[field]).exists()
            )
            if missing:
                gaps[f"{provider}:{dataset['name']}"] = missing
    return gaps


def test_no_new_dataset_declares_a_missing_artifact():
    """A dataset may not declare an artifact it does not ship unless it is a known gap."""
    unexpected = {
        name: fields
        for name, fields in _declared_artifact_gaps().items()
        if name not in KNOWN_INCOMPLETE
    }
    assert not unexpected, (
        "These datasets declare validation artifacts that do not exist on disk:\n"
        + "\n".join(
            f"  {n}: missing {', '.join(f)}" for n, f in sorted(unexpected.items())
        )
        + "\n\nCommit the artifacts (see hvantk/skills/_conventions/SKILL.md), or add an "
        "entry to KNOWN_INCOMPLETE with the reason."
    )


def test_known_incomplete_ledger_is_not_stale():
    """Once a dataset ships everything, it must be dropped from the ledger."""
    gaps = _declared_artifact_gaps()
    now_complete = sorted(name for name in KNOWN_INCOMPLETE if name not in gaps)
    assert not now_complete, (
        "These datasets now ship every declared artifact and must be removed from "
        f"KNOWN_INCOMPLETE: {', '.join(now_complete)}"
    )


@pytest.mark.parametrize("name", sorted(KNOWN_INCOMPLETE))
def test_known_gap_matches_reality(name: str):
    """The recorded fields must match what is actually absent, so the ledger stays honest."""
    actual = _declared_artifact_gaps().get(name, ())
    assert set(actual) == set(KNOWN_INCOMPLETE[name]), (
        f"{name}: ledger says {sorted(KNOWN_INCOMPLETE[name])}, "
        f"disk says {sorted(actual)}"
    )


def test_every_known_gap_is_classified_permanent():
    """A dataset may only sit on the ledger with a written reason it can never leave it.

    The ledger's original third cause was "simply never seeded", which is not an
    exemption but a TODO -- and a TODO parked in an exemption list is how five datasets
    came to have no executable contract, which is what made them ungradable by the
    agent-authoring evaluation (#341). Requiring a ``PERMANENTLY_UNGRADABLE`` entry
    forces that distinction to be made explicitly at the moment a dataset is added.
    """
    # A blank or whitespace reason is not a reason. Comparing keys alone would let
    # PERMANENTLY_UNGRADABLE[name] = "" satisfy the invariant while explaining nothing.
    unclassified = sorted(
        name
        for name in KNOWN_INCOMPLETE
        if not str(PERMANENTLY_UNGRADABLE.get(name, "")).strip()
    )
    assert not unclassified, (
        "These datasets are on KNOWN_INCOMPLETE without a recorded reason they can "
        f"never ship the artifacts: {', '.join(unclassified)}.\n"
        "If the real reason is 'not seeded yet', seed it instead of listing it."
    )
    stale = sorted(set(PERMANENTLY_UNGRADABLE) - set(KNOWN_INCOMPLETE))
    assert not stale, (
        "These datasets carry a permanent-exemption reason but are no longer on "
        f"KNOWN_INCOMPLETE: {', '.join(stale)}. Remove the reason too."
    )
